Repository AztecGameLab/LongTermGame5, pull requests merged in 2021-02, with the labels that each got.

#3 Names #2
  .DS_Store
  ThePeople/AlecGraham.txt
  ThePeople/Andres Maturin.txt
  ThePeople/ArcherHovey.txt
  ThePeople/BrandonAltamirano.txt
  ThePeople/BrandonRendon.txt
  ThePeople/ColeKincaid.txt
  ThePeople/DanBlackford.txt
  ThePeople/DanielWalls.txt
  ThePeople/JacobFactora.txt
  ThePeople/JamesLee.txt
  ThePeople/JamesMaron.rtf
  ThePeople/JosephTomada.txt
  ThePeople/JoshuaSantos.txt
  ThePeople/KennyNguyen.txt
  ThePeople/MatthewMorisky.txt
  ThePeople/MatthewWantoch.txt
  ThePeople/Mercedesortegatxt.pdf
  ThePeople/NaseemTahbaz.txt
  ThePeople/NickChen.txt
  ThePeople/Ryan Coughlin.txt
  ThePeople/RyanWright.txt
  ThePeople/RynSchroeder.txt
  ThePeople/SophiaCanja.txt
  ThePeople/VikhyatModgil.txt
  ThePeople/XzavierCaldwell.txt
  ThePeople/YousifJabbo.txt
Labels: enhancement

#79 Mana UI and Mana System
  Assets/Scenes/ManaScene.unity
  Assets/Scenes/ManaScene.unity.meta
  Assets/Scripts/ManaBarUI.cs
  Assets/Scripts/ManaBarUI.cs.meta
  Assets/Scripts/ManaSystem.cs
  Assets/Scripts/ManaSystem.cs.meta
  Assets/Sprites.meta
  Assets/Sprites/ManaBarUI.png
  Assets/Sprites/ManaBarUI.png.meta
Labels: Feature, Player, UI

#87 Parallax Effect
  Assets/Scenes/ParallaxScene.unity
  Assets/Scenes/ParallaxScene.unity.meta
  Assets/Scripts/ParallaxEffect.cs
  Assets/Scripts/ParallaxEffect.cs.meta
  Assets/Scripts/TempController.cs
  Assets/Scripts/TempController.cs.meta
  Assets/Sprites/Dev.meta
  Assets/Sprites/Dev/Platform.png
  Assets/Sprites/Dev/Platform.png.meta
  Assets/Sprites/Dev/Player.png
  Assets/Sprites/Dev/Player.png.meta
  Assets/Sprites/Dev/parallax-mountain-bg.png
  Assets/Sprites/Dev/parallax-mountain-bg.png.meta
  Assets/Sprites/Dev/parallax-mountain-foreground-trees.png
  Assets/Sprites/Dev/parallax-mountain-foreground-trees.png.meta
  Assets/Sprites/Dev/parallax-mountain-montain-far.png
  Assets/Sprites/Dev/parallax-mountain-montain-far.png.meta
  Assets/Sprites/Dev/parallax-mountain-mountains.png
  Assets/Sprites/Dev/parallax-mountain-mountains.png.meta
  Assets/Sprites/Dev/parallax-mountain-trees.png
  Assets/Sprites/Dev/parallax-mountain-trees.png.meta
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/TagManager.asset
Labels: Aesthetic, Feature

#80 Crumbling Platform SFX.wav
  Assets/Audio/Environmental_Hazards_SFX/crumbling_platform_SFX.wav
Labels: Audio

#90 Save system
  .idea/.idea.LongTermGame5/.idea/.gitignore
  .vscode/launch.json
  Assets/Scenes/SavingTest.meta
  Assets/Scenes/SavingTest/SaveTest.unity
  Assets/Scenes/SavingTest/SaveTest.unity.meta
  Assets/Scenes/SavingTest/SaveTest2.unity
  Assets/Scenes/SavingTest/SaveTest2.unity.meta
  Assets/Scenes/SavingTest/SaveTest3.unity
  Assets/Scenes/SavingTest/SaveTest3.unity.meta
  Assets/Scripts/Attributes.meta
  Assets/Scripts/Attributes/ReadOnlyAttribute.cs
  Assets/Scripts/Attributes/ReadOnlyAttribute.cs.meta
  Assets/Scripts/SaveSystem.meta
  Assets/Scripts/SaveSystem/ISaveableComponent.cs
  Assets/Scripts/SaveSystem/ISaveableComponent.cs.meta
  Assets/Scripts/SaveSystem/SaveData.cs
  Assets/Scripts/SaveSystem/SaveData.cs.meta
  Assets/Scripts/SaveSystem/SaveLoad.cs
  Assets/Scripts/SaveSystem/SaveLoad.cs.meta
  Assets/Scripts/SaveSystem/SaveableGameObject.cs
  Assets/Scripts/SaveSystem/SaveableGameObject.cs.meta
  Assets/Scripts/SaveSystem/exampleClasses.meta
  Assets/Scripts/SaveSystem/exampleClasses/SaveableEntityExample.cs
  Assets/Scripts/SaveSystem/exampleClasses/SaveableEntityExample.cs.meta
  Assets/Scripts/SaveSystem/exampleClasses/SaveablePlayerExample.cs
  Assets/Scripts/SaveSystem/exampleClasses/SaveablePlayerExample.cs.meta
  Assets/Scripts/SaveSystem/exampleClasses/SceneSaverExample.cs
  Assets/Scripts/SaveSystem/exampleClasses/SceneSaverExample.cs.meta
  Assets/Scripts/SaveSystem/examplePrefabs.meta
  Assets/Scripts/SaveSystem/examplePrefabs/saveableEnemyExample.prefab
  Assets/Scripts/SaveSystem/examplePrefabs/saveableEnemyExample.prefab.meta
  Assets/Scripts/SaveSystem/examplePrefabs/saveablePlayerExample.prefab
  Assets/Scripts/SaveSystem/examplePrefabs/saveablePlayerExample.prefab.meta
  Assets/Scripts/SaveSystem/oldSaveDataAttribute.cs
  Assets/Scripts/SaveSystem/oldSaveDataAttribute.cs.meta
  ProjectSettings/ProjectSettings.asset
Labels: Feature, Game Management
