Repository AztecGameLab/LongTermGame5, pull requests merged in 2021-03, with the labels that each got.

#105 Fix the entity script to tell it to die
  Assets/Scripts/BaseCode/Entity.cs
Labels: bug

#108 Interactables
  .gitignore
  Assets/Audio/Environmental_Hazards_SFX/crumbling_platform.wav.meta
  Assets/Audio/Environmental_Hazards_SFX/crumbling_platform_warning_wobble.wav.meta
  Assets/Prefabs/SavePoint.prefab
  Assets/Prefabs/TempPlayer.prefab
  Assets/Scenes/Interactables.unity
  Assets/Scenes/Interactables.unity.meta
  Assets/Scripts/BaseCode/GameInputs.cs
  Assets/Scripts/BaseCode/GameInputs.cs.meta
  Assets/Scripts/BaseCode/GameInputs.inputactions
  Assets/Scripts/BaseCode/GameInputs.inputactions.meta
  Assets/Scripts/BaseCode/Interactable.cs
  Assets/Scripts/BaseCode/PlatformerController.cs
  Assets/Scripts/Editor.meta
  Assets/Scripts/Editor/CustomMenuItems.cs
  Assets/Scripts/Editor/CustomMenuItems.cs.meta
  Assets/Scripts/Interactable.cs
  Assets/Scripts/Interactable.cs.meta
  Assets/Scripts/SaveSystem/SavePoint.cs
  Assets/Scripts/Scanner.cs
  Assets/Scripts/Scanner.cs.meta
  Assets/Scripts/StaticWrapper.asset
  Assets/Scripts/StaticWrapper.asset.meta
  Assets/Scripts/StaticWrapper.cs
  Assets/Scripts/StaticWrapper.cs.meta
  Assets/Scripts/Trigger.cs
  Assets/Scripts/Trigger.cs.meta
  Assets/Sprites/Dev/Button_Entry.anim
  Assets/Sprites/Dev/Button_Entry.anim.meta
  Assets/Sprites/Dev/Button_ToggleDown.anim
  Assets/Sprites/Dev/Button_ToggleDown.anim.meta
  Assets/Sprites/Dev/Button_ToggleUp.anim
  Assets/Sprites/Dev/Button_ToggleUp.anim.meta
  Assets/Sprites/Dev/Debug Button.png
  Assets/Sprites/Dev/Debug Button.png.meta
  Assets/Sprites/Dev/Sprite.controller
  Assets/Sprites/Dev/Sprite.controller.meta
Labels: Game Management

#115 Added Grapple Hook Sounds
  .DS_Store
  Assets/.DS_Store
  Assets/Audio/.DS_Store
  Assets/Audio/Grapple Hook.meta
  Assets/Audio/Grapple Hook/Grapple_All_Together.wav
  Assets/Audio/Grapple Hook/Grapple_All_Together.wav.meta
  Assets/Audio/Grapple Hook/Grapple_Hit_1.wav
  Assets/Audio/Grapple Hook/Grapple_Hit_1.wav.meta
  Assets/Audio/Grapple Hook/Grapple_Hit_2.wav
  Assets/Audio/Grapple Hook/Grapple_Hit_2.wav.meta
  Assets/Audio/Grapple Hook/Grapple_Loop.wav
  Assets/Audio/Grapple Hook/Grapple_Loop.wav.meta
  Assets/Audio/Grapple Hook/Grapple_Shot_1.wav
  Assets/Audio/Grapple Hook/Grapple_Shot_1.wav.meta
  Assets/Audio/Grapple Hook/Grapple_Shot_2.wav
  Assets/Audio/Grapple Hook/Grapple_Shot_2.wav.meta
  Assets/Audio/Grapple Hook/Grapple_Snap_New_1.wav
  Assets/Audio/Grapple Hook/Grapple_Snap_New_1.wav.meta
  Assets/Audio/Player Movement.meta
  Assets/Audio/Player Movement/Dash.wav
  Assets/Audio/Player Movement/Dash.wav.meta
  Assets/Audio/Player Movement/Jump.wav
  Assets/Audio/Player Movement/Jump.wav.meta
  Assets/Audio/Player Movement/footstep1.wav
  Assets/Audio/Player Movement/footstep1.wav.meta
  Assets/Audio/Player Movement/footstep2.wav
  Assets/Audio/Player Movement/footstep2.wav.meta
  Assets/Audio/Player Movement/jump_landing.wav
  Assets/Audio/Player Movement/jump_landing.wav.meta
  Assets/Audio/Test Folder (Grapple Snap).meta
  Assets/Audio/Test Folder (Grapple Snap)/Grapple_Snap_New_1.wav
  Assets/Audio/Test Folder (Grapple Snap)/Grapple_Snap_New_1.wav.meta
Labels: Feature

#123 Flying enemy
  Assets/Prefabs/Flying Enemy.meta
  Assets/Prefabs/Flying Enemy/Flying Enemy Projectile.prefab
  Assets/Prefabs/Flying Enemy/Flying Enemy Projectile.prefab.meta
  Assets/Prefabs/Flying Enemy/Flying Enemy.prefab
  Assets/Prefabs/Flying Enemy/Flying Enemy.prefab.meta
  Assets/Scenes/FlyingEnemyScene.unity
  Assets/Scenes/FlyingEnemyScene.unity.meta
  Assets/Scripts/Enemies.meta
  Assets/Scripts/Enemies/FlyingEnemyMovement.cs
  Assets/Scripts/Enemies/FlyingEnemyMovement.cs.meta
  Assets/Scripts/Enemies/FlyingEnemyProjectile.cs
  Assets/Scripts/Enemies/FlyingEnemyProjectile.cs.meta
Labels: Enemies

#84 ManaBarUI and ManaSystem Updates
  Assets/Scenes/ManaScene.unity
  Assets/Scripts/FillBarUI.cs
  Assets/Scripts/FillBarUI.cs.meta
  Assets/Scripts/FillSystem.cs
  Assets/Scripts/FillSystem.cs.meta
  Assets/Scripts/ManaBarUI.cs
  Assets/Scripts/ManaSystem.cs
  Assets/Sprites/FillBarUI.png
  Assets/Sprites/FillBarUI.png.meta
Labels: Player, UI, Upgrade

#152 Updating the Player Controller
  .vscode/launch.json
  Assets/PlayerControllerTestAssets.meta
  Assets/Prefabs/TempPlayer.prefab
  Assets/Scenes/PlayerTestScene.unity
  Assets/Scripts/BaseCode/PlatformerController.cs
  Assets/Scripts/BaseCode/PlatformerParameters.asset
  Assets/Scripts/BaseCode/PlatformerParameters.cs
  ProjectSettings/EditorBuildSettings.asset
Labels: Upgrade, bug

#154 Additional fixes to the BarSystemUI
  Assets/Scripts/FillBarUI.cs
  Assets/Scripts/FillSystem.cs
Labels: UI, Upgrade

#153 Made a few changes to entity scripts
  Assets/PlayerControllerTestAssets.meta
  Assets/Scripts/BaseCode/Entity.cs
  Assets/Scripts/BaseCode/PlatformerController.cs
Labels: Enemies, Upgrade

#160 Audio branch - Grapple Hook REVISED Sounds
  .DS_Store
  Assets/.DS_Store
  Assets/Audio/.DS_Store
  Assets/Audio/Double Jump/Double Jump.wav
  Assets/Audio/Grapple Hook/Grapple_All_Together_Sample_REVISED.wav
  Assets/Audio/Grapple Hook/Grapple_Hit_1_REVISED.wav
  Assets/Audio/Grapple Hook/Grapple_Hit_2_REVISED.wav
  Assets/Audio/Grapple Hook/Grapple_Loop_REVISED.wav
Labels: Feature

#161 Ground Pound Ability
  .DS_Store
  Assets/Prefabs/TempPlayer.prefab
  Assets/Scenes/GroundPound.unity
  Assets/Scenes/GroundPound.unity.meta
  Assets/Scripts/BaseCode/PlatformerController.cs
  Assets/Scripts/GroundPound.cs
  Assets/Scripts/GroundPound.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/PackageManagerSettings.asset
Labels: Abilities, Feature

#166 Finished Whale God
  Assets/Animations/WaterGod/idle.anim
  Assets/Animations/WaterGod/whale sprite 1.controller
  Assets/Scenes/GodSpriteScene.unity
Labels: Animation

#174 Updated the Projectile Weapons to have a direction parameter
  Assets/Scenes/PlayerTestScene.unity
  Assets/Scripts/BaseCode/GameInputs.inputactions.meta
  Assets/Scripts/BaseCode/PlatformerController.cs
  Assets/Scripts/BaseCode/PlatformerParameters.asset
  Assets/Scripts/BaseCode/PlatformerParameters.cs
  Assets/Scripts/BaseCode/ProjectileWeapon.cs
Labels: Player, Upgrade

#164 Spikes #99
  Assets/Audio/Double Jump.meta
  Assets/Audio/Grapple Hook/Grapple_All_Together_Sample_REVISED.wav.meta
  Assets/Audio/Grapple Hook/Grapple_Hit_1_REVISED.wav.meta
  Assets/Audio/Grapple Hook/Grapple_Hit_2_REVISED.wav.meta
  Assets/Audio/Grapple Hook/Grapple_Loop_REVISED.wav.meta
  Assets/Prefabs/Spikes.prefab
  Assets/Prefabs/Spikes.prefab.meta
  Assets/Scenes/Spikes.unity
  Assets/Scenes/Spikes.unity.meta
  Assets/Scripts/BaseCode/PlatformerController.cs
  Assets/Scripts/SpikeScript.cs
  Assets/Scripts/SpikeScript.cs.meta
  Assets/Sprites/spike.png
  Assets/Sprites/spike.png.meta
Labels: Environment

#185 Flying enemy
  Assets/Prefabs/Flying Enemy/Flying Enemy.prefab
  Assets/Scenes/FlyingEnemyScene.unity
  Assets/Scripts/Enemies/FlyingEnemyMovement.cs
  Assets/Scripts/Enemies/FlyingEnemyProjectile.cs
Labels: Enemies

#196 Art assets
  Assets/Animations/MushroomBounce.meta
  Assets/Animations/MushroomBounce/Bounce.anim
  Assets/Animations/MushroomBounce/Bounce.anim.meta
  Assets/Animations/MushroomBounce/Mushroom.controller
  Assets/Animations/MushroomBounce/Mushroom.controller.meta
  Assets/Animations/MushroomBounce/sittingStill.anim
  Assets/Animations/MushroomBounce/sittingStill.anim.meta
  Assets/Animations/Torch/TorchController.controller
  Assets/Animations/Torch/TorchController.controller.meta
  Assets/Prefabs/Props/Mushroom.prefab
  Assets/Prefabs/Props/Mushroom.prefab.meta
  Assets/Scenes/GodSpriteScene.unity
  Assets/Sprites/Fox_Statue/FoxStatue.png
  Assets/Sprites/Fox_Statue/FoxStatue_emmissive.png
  Assets/Sprites/Mushroom_Bounce.meta
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0000.png
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0000.png.meta
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0001.png
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0001.png.meta
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0002.png
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0002.png.meta
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0003.png
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0003.png.meta
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0004.png
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0004.png.meta
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0005.png
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0005.png.meta
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0006.png
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0006.png.meta
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0007.png
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0007.png.meta
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0008.png
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0008.png.meta
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0009.png
  Assets/Sprites/Mushroom_Bounce/MushroomBounce_0009.png.meta
  Assets/Sprites/OneWayDestructable/OneWayDestructableBG.png
  Assets/Sprites/OneWayDestructable/OneWayDestructableCrackBot.png
  Assets/Sprites/OneWayDestructable/OneWayDestructableCrackLeft.png
  Assets/Sprites/OneWayDestructable/OneWayDestructableCrackRight.png
  Assets/Sprites/OneWayDestructable/OneWayDestructableCrackTop.png
  Assets/Sprites/windParticles.png
Labels: Animation

#184 Door script
  Assets/Prefabs/Door.prefab
  Assets/Prefabs/Door.prefab.meta
  Assets/Scenes/OneWayDoor.unity
  Assets/Scenes/OneWayDoor.unity.meta
  Assets/Scripts/Door.cs
  Assets/Scripts/Door.cs.meta
Labels: Environment

#225 Elevator
  Assets/Prefabs/Elevator.prefab
  Assets/Prefabs/Elevator.prefab.meta
  Assets/Scenes/ElevatorTest.unity
  Assets/Scenes/ElevatorTest.unity.meta
  Assets/Scripts/Elevator.cs
  Assets/Scripts/Elevator.cs.meta
Labels: Environment

#245 created an Ability base class for implementing abilities.
  Assets/Scripts/Ability.cs
  Assets/Scripts/Ability.cs.meta
  Assets/Scripts/BaseCode/GameInputs.inputactions.meta
  Assets/Scripts/BaseCode/PlatformerController.cs
  Assets/Scripts/TestAbility.cs
  Assets/Scripts/TestAbility.cs.meta
Labels: Abilities
