Repository AztecGameLab/LongTermGame5, pull requests merged in 2021-04, with the labels that each got.

#249 Invincible enemy
  Assets/Animations/Enemies.meta
  Assets/Animations/Enemies/InvincibleEnemy.meta
  Assets/Animations/Enemies/InvincibleEnemy/InvincibleEnemy.controller
  Assets/Animations/Enemies/InvincibleEnemy/InvincibleEnemy.controller.meta
  Assets/Animations/Enemies/InvincibleEnemy/InvincibleIdle.anim
  Assets/Animations/Enemies/InvincibleEnemy/InvincibleIdle.anim.meta
  Assets/Animations/Enemies/InvincibleEnemy/InvincibleJumpLeft.anim
  Assets/Animations/Enemies/InvincibleEnemy/InvincibleJumpLeft.anim.meta
  Assets/Animations/Enemies/InvincibleEnemy/InvincibleJumpRight.anim
  Assets/Animations/Enemies/InvincibleEnemy/InvincibleJumpRight.anim.meta
  Assets/Prefabs/InvincibleEnemy.prefab
  Assets/Prefabs/InvincibleEnemy.prefab.meta
  Assets/Scenes/InvincibleEnemyTestScene.unity
  Assets/Scenes/InvincibleEnemyTestScene.unity.meta
  Assets/Scripts/InvincibleEnemy.cs
  Assets/Scripts/InvincibleEnemy.cs.meta
  Assets/Sprites/Dev/SpriteTemplate64.png
  Assets/Sprites/Dev/SpriteTemplate64.png.meta
  Assets/Sprites/Dev/TileSprites.meta
  Assets/Sprites/Dev/TileSprites/SpriteTemplate64_0.asset
  Assets/Sprites/Dev/TileSprites/SpriteTemplate64_0.asset.meta
  Assets/Sprites/Dev/TileSprites/SpriteTemplate64_1.asset
  Assets/Sprites/Dev/TileSprites/SpriteTemplate64_1.asset.meta
  Assets/Sprites/Dev/TileSprites/SpriteTemplate64_2.asset
  Assets/Sprites/Dev/TileSprites/SpriteTemplate64_2.asset.meta
  Assets/Sprites/Dev/TileSprites/SpriteTemplate64_3.asset
  Assets/Sprites/Dev/TileSprites/SpriteTemplate64_3.asset.meta
Labels: Animation, Enemies, NPC

#255 Testing Art Assets 2.0
  Assets/Scenes/GodSpriteScene.unity
Labels: Animation

#279 Bash ability and Camera system
  Assets/2D Shake.asset
  Assets/2D Shake.asset.meta
  Assets/Audio/Fire Ground Pound.meta
  Assets/Menu Camera Noise Profile.asset
  Assets/Menu Camera Noise Profile.asset.meta
  Assets/Prefabs/Flying Enemy/Flying Enemy Projectile.prefab
  Assets/Prefabs/LevelDesignPrefabs/AdditionalCameraSetup.prefab
  Assets/Prefabs/LevelDesignPrefabs/AdditionalCameraSetup.prefab.meta
  Assets/Prefabs/Player Camera.prefab
  Assets/Prefabs/Player Camera.prefab.meta
  Assets/Resources/FasterPlayer.asset
  Assets/Resources/FasterPlayer.asset.meta
  Assets/Resources/Levels/BashTest.asset
  Assets/Resources/Levels/BashTest.asset.meta
  Assets/Resources/TempPlayer.prefab
  Assets/Scenes/BashTest.unity
  Assets/Scenes/BashTest.unity.meta
  Assets/Scenes/LevelLoadTest/Bridge 1.unity
  Assets/Scenes/LevelLoadTest/Bridge 2.unity
  Assets/Scenes/LevelLoadTest/Hub 1.unity
  Assets/Scenes/LevelLoadTest/Hub 2.unity
  Assets/Scenes/LevelLoadTest/Hub 3.unity
  Assets/Scenes/Persistent.unity
  Assets/Scenes/Persistent.unity.meta
  Assets/Scripts/BaseCode/GameInputs.cs
  Assets/Scripts/BaseCode/GameInputs.inputactions
  Assets/Scripts/BaseCode/PlatformerController.cs
  Assets/Scripts/BashAbility.cs
  Assets/Scripts/BashAbility.cs.meta
  Assets/Scripts/CameraShake.cs
  Assets/Scripts/Editor/CustomMenuItems.cs
  Assets/Scripts/Editor/LevelToolkitWindow.cs
  Assets/Scripts/IBashable.cs
  Assets/Scripts/IBashable.cs.meta
  Assets/Scripts/LevelSystem/LevelController.cs
  Assets/Scripts/LevelSystem/LevelLoadTrigger.cs
  Assets/Scripts/LevelSystem/LevelUtil.cs
  Assets/Scripts/ParallaxEffect.cs
  Assets/Scripts/PlayerCamera.cs
  Assets/Scripts/PlayerCamera.cs.meta
  Assets/Scripts/SaveSystem/SaveListener.cs
  Assets/Scripts/Scanner.cs
  Assets/Scripts/SimpleBashable.cs
  Assets/Scripts/SimpleBashable.cs.meta
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/BurstAotSettings_Android.json
  ProjectSettings/BurstAotSettings_StandaloneWindows.json
  ProjectSettings/BurstAotSettings_WebGL.json
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/PackageManagerSettings.asset
  ProjectSettings/TagManager.asset
Labels: Abilities, Feature

#286 Button Entity
  Assets/Prefabs/LevelDesignPrefabs/Environment/Interactable/BulletTrigger.prefab
  Assets/Prefabs/LevelDesignPrefabs/Environment/Interactable/BulletTrigger.prefab.meta
  Assets/Prefabs/LevelDesignPrefabs/Environment/Interactable/MovingPlatform.prefab
  Assets/Prefabs/LevelDesignPrefabs/Environment/Interactable/MovingPlatform.prefab.meta
  Assets/Resources/Levels/Target Test.asset
  Assets/Resources/Levels/Target Test.asset.meta
  Assets/Scenes/Target Test.unity
  Assets/Scenes/Target Test.unity.meta
  Assets/Scripts/ButtonEntity.cs
  Assets/Scripts/ButtonEntity.cs.meta
  Assets/Sprites/ShootableButton.meta
  Assets/Sprites/ShootableButton/ShootableButton.png
  Assets/Sprites/ShootableButton/ShootableButton.png.meta
  Assets/Sprites/ShootableButton/ShootableButtonEmis.png
  Assets/Sprites/ShootableButton/ShootableButtonEmis.png.meta
  Assets/Sprites/ShootableButton/ShootableButtonEmisWhite.png
  Assets/Sprites/ShootableButton/ShootableButtonEmisWhite.png.meta
Labels: Feature

#287 Bash ability hotfix
  Assets/Resources/TempPlayer.prefab
  Assets/Scenes/LevelLoadTest/Hub 1.unity
  Assets/Scripts/Ability.cs
  Assets/Scripts/Fader.cs
  Assets/Scripts/MainMenuUI.cs
  Assets/Scripts/SolidColorFader.cs
  Assets/Scripts/TransitionController.cs
Labels: bug

#292 Destructable enhancements
  Assets/Prefabs/DestructableExample.asset
  Assets/Prefabs/DestructableExample.asset.meta
  Assets/Prefabs/DestructableExample.prefab
  Assets/Scripts/Destructible.cs
Labels: Environment

#291 Fixed Bug where player was stuck in aiming when hit
  .xmodmap.orig
  Assets/Resources/GameInputs.cs
  Assets/Resources/GameInputs.cs.meta
  Assets/Resources/GameInputs.inputactions
  Assets/Resources/GameInputs.inputactions.meta
  Assets/Resources/Weapons.meta
  Assets/Resources/Weapons/FireBall.asset
  Assets/Resources/Weapons/FireBall.asset.meta
  Assets/Resources/Weapons/Ricochet.asset
  Assets/Resources/Weapons/Ricochet.asset.meta
  Assets/Scripts/BaseCode/PlatformerController.cs
  Assets/Scripts/BaseCode/ProjectileWeapon.cs
  Assets/Scripts/GrappScript.cs
  Assets/Scripts/Ricochet.cs
  Assets/Scripts/SlideAbility.cs
  fmod_editor.log
Labels: bug

#317 Changed quill projectile
  Assets/Sprites/MovingPlatform/Rock_Platform_GRASS_LONG.png
  Assets/Sprites/MovingPlatform/Rock_Platform_GRASS_SMALL.png
  Assets/Sprites/MovingPlatform/Rock_Platform_LONG.png
  Assets/Sprites/MovingPlatform/Rock_Platform_SMALL.png
  Assets/Sprites/QuillProjectile.png
  Assets/Sprites/UI/Checkbox_UI.png
  Assets/Sprites/UI/Circle_UI.png
  Assets/Sprites/UI/Decoration_UI.png
  Assets/Sprites/UI/DialogBox_UI/Air_DialogBox_UI.png
  Assets/Sprites/UI/DialogBox_UI/Earth_DialogBox_UI.png
  Assets/Sprites/UI/DialogBox_UI/Fire_DialogBox_UI.png
  Assets/Sprites/UI/DialogBox_UI/Water_DialogBox_UI.png
  Assets/Sprites/UI/Health_Bar_EMPTY_UI.png
  Assets/Sprites/UI/Health_UI/HEALTH_10%_UI.png
  Assets/Sprites/UI/Health_UI/HEALTH_100%_UI.png
  Assets/Sprites/UI/Health_UI/HEALTH_20%_UI.png
  Assets/Sprites/UI/Health_UI/HEALTH_30%_UI.png
  Assets/Sprites/UI/Health_UI/HEALTH_40%_UI.png
  Assets/Sprites/UI/Health_UI/HEALTH_50%_UI.png
  Assets/Sprites/UI/Health_UI/HEALTH_60%_UI.png
  Assets/Sprites/UI/Health_UI/HEALTH_70%_UI.png
  Assets/Sprites/UI/Health_UI/HEALTH_80%_UI.png
  Assets/Sprites/UI/Health_UI/HEALTH_90%_UI.png
  Assets/Sprites/UI/Mana_UI/MANA_100%_UI.png
  Assets/Sprites/UI/Mana_UI/MANA_20%_UI.png
  Assets/Sprites/UI/Mana_UI/MANA_30%_UI.png
  Assets/Sprites/UI/Mana_UI/MANA_40%_UI.png
  Assets/Sprites/UI/Mana_UI/MANA_50%_UI.png
  Assets/Sprites/UI/Mana_UI/MANA_60%_UI.png
  Assets/Sprites/UI/Mana_UI/MANA_70%_UI.png
  Assets/Sprites/UI/Mana_UI/MANA_80%_UI.png
  Assets/Sprites/UI/Mana_UI/MANA_90%_UI.png
  Assets/Sprites/UI/SliderStick_UI.png
  Assets/Sprites/UI/Slider_Button_UI.png
  Assets/Sprites/UI/X_UI.png
Labels: Aesthetic

#323 Minor changes and adjustments. Fireball must be able to reach all platforms without a double jump.
  Assets/Scenes/GameScenes/4FireBallLockKey.unity
Labels: Environment

#319 Air hub and 1/5 lock and key
  Assets/Resources/Levels/1&5SlideDoubleJumpLockKey.asset
  Assets/Resources/Levels/1&5SlideDoubleJumpLockKey.asset.meta
  Assets/Scenes/GameScenes/1&5SlideDoubleJumpLockKey.unity
  Assets/Scenes/GameScenes/AirHub.unity
Labels: Environment

#310 Invincible enemy
  Assets/Prefabs/InvincibleEnemy.prefab
  Assets/Resources/Levels/InvincibleEnemyTestScene.asset
  Assets/Resources/Levels/InvincibleEnemyTestScene.asset.meta
  Assets/Scenes/InvincibleEnemyTestScene.unity
  Assets/Scripts/InvincibleEnemy.cs
Labels: Audio, Enemies

#288 Healing ability
  Assets/Animations/Kappi/TempPlayer.controller
  Assets/Animations/Kappi/heal.anim
  Assets/Animations/Kappi/jump.anim
  Assets/Prefabs/Flying Enemy/Flying Enemy Projectile.prefab
  Assets/Prefabs/LevelDesignPrefabs/Enemies/AirEnemy.prefab
  Assets/Prefabs/LevelDesignPrefabs/Enemies/FireEnemy.prefab
  Assets/Prefabs/LevelDesignPrefabs/Enemies/NatureEnemy.prefab
  Assets/Prefabs/LevelDesignPrefabs/Enemies/WaterEnemy.prefab
  Assets/Prefabs/LevelDesignPrefabs/Environment/BouncyMushroom.prefab
  Assets/Prefabs/LevelDesignPrefabs/Environment/Hazard/Spikes.prefab
  Assets/Resources/GameInputs.cs
  Assets/Resources/GameInputs.inputactions
  Assets/Resources/Levels/Healing Test.asset
  Assets/Resources/Levels/Healing Test.asset.meta
  Assets/Resources/TempPlayer.prefab
  Assets/Scenes/Healing Test.unity
  Assets/Scenes/Healing Test.unity.meta
  Assets/Scenes/MVPShowcaseScene.unity
  Assets/Scenes/Persistent.unity
  Assets/Scripts/Ability.cs
  Assets/Scripts/AnimationCurveHelper.cs
  Assets/Scripts/CameraController.cs
  Assets/Scripts/CameraController.cs.meta
  Assets/Scripts/HealingAbility.cs
  Assets/Scripts/HealingAbility.cs.meta
  Assets/Scripts/LevelSystem/LevelController.cs
  Assets/Scripts/SimpleBashable.cs
  Assets/Scripts/SpikeScript.cs
  Assets/Scripts/bouncy.cs
Labels: Abilities

#327 Player death
  Assets/Other/New 2D Renderer Data.asset
  Assets/Scenes/LevelLoadTest/Hub 1.unity
  Assets/Scenes/LevelLoadTest/Hub 2.unity
  Assets/Scenes/Persistent.unity
  Assets/Scripts/BaseCode/PlatformerController.cs
  Assets/Scripts/LevelSystem/LevelController.cs
  Assets/Scripts/LevelSystem/LevelUtil.cs
  Assets/Scripts/MainMenuUI.cs
Labels: Player

#335 Fix Slide Ability able to be used when locked
  Assets/Scripts/SlideAbility.cs
Labels: bug

#343 Misc fixes
  Assets/Other/UniversalRenderPipelineAsset.asset
  Assets/Plugins/FMOD/Resources/FMODStudioSettings.asset
  Assets/Prefabs/ManaOrb.prefab
  Assets/Resources/GameInputs.cs
  Assets/Resources/GameInputs.inputactions
  Assets/Resources/Levels/1&5SlideDoubleJumpLockKey.asset
  Assets/Resources/Levels/6FreezeLockKey.asset
  Assets/Resources/Levels/AirHub.asset
  Assets/Resources/Levels/FireHub.asset
  Assets/Resources/Levels/WaterHub.asset
  Assets/Resources/TempPlayer.prefab
  Assets/Scenes/Persistent.unity
  Assets/Scripts/Ability.cs
  Assets/Scripts/AbilityUnlocks.cs
  Assets/Scripts/BaseCode/PlatformerController.cs
  Assets/Scripts/BashAbility.cs
  Assets/Scripts/BulkyEnemy.cs
  Assets/Scripts/Editor/CutsceneEditor.cs
  Assets/Scripts/Editor/CutsceneEditor.cs.meta
  Assets/Scripts/Editor/CutsceneElementEditor.cs
  Assets/Scripts/Editor/CutsceneElementEditor.cs.meta
  Assets/Scripts/Editor/EditorSceneSetupController.cs
  Assets/Scripts/Enemies/FlyingEnemyMovement.cs
  Assets/Scripts/Enemies/FlyingEnemyProjectile.cs
  Assets/Scripts/FillBarUI.cs
  Assets/Scripts/FireBallCollider.cs
  Assets/Scripts/GameplayEventChannel.cs
  Assets/Scripts/GameplayEventChannel.cs.meta
  Assets/Scripts/HealingAbility.cs
  Assets/Scripts/LevelSystem/LevelController.cs
  Assets/Scripts/LevelSystem/LevelUtil.cs
  Assets/Scripts/MainMenuUI.cs
  Assets/Scripts/ManaController.cs
  Assets/Scripts/ManaController.cs.meta
  Assets/Scripts/ManaPickup.cs
  Assets/Scripts/ManaSystem.cs
  Assets/Scripts/ManaSystem.cs.meta
  Assets/Scripts/PlayerCamera.cs
  Assets/StreamingAssets.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/ProjectSettings.asset
  ProjectSettings/QualitySettings.asset
Labels: Upgrade

#345 Air hub and 1/5 lock and key
  Assets/Scenes/GameScenes/1&5SlideDoubleJumpLockKey.unity
  Assets/Scenes/GameScenes/AirHub.unity
  fmod_editor.log
Labels: Environment

#350 I "think" I fixed the jumping problem?
  Assets/Scripts/BaseCode/PlatformerController.cs
  Assets/Sprites/Backgrounds/grove of tranquility.psb.meta
  Assets/Sprites/Backgrounds/infernal valley.psb.meta
  Assets/Sprites/Backgrounds/luminescent bog.psb.meta
  Assets/Sprites/Backgrounds/nimbus mountains.psb.meta
  Assets/Sprites/Prologue.meta
Labels: bug

#349 Weapon switching
  Assets/Resources/GameInputs.cs
  Assets/Resources/GameInputs.inputactions
  Assets/Resources/Levels/4FireballLockKey.asset.meta
  Assets/Resources/TempPlayer.prefab
  Assets/Scenes/GameScenes/4FireBallLockKey.unity
  Assets/Scripts/BaseCode/PlatformerController.cs
  Assets/Scripts/BaseCode/ProjectileWeapon.cs
  Assets/Scripts/GrappScript.cs
  Assets/Scripts/SlideAbility.cs
  Assets/Scripts/WeaponSwitchAbility.cs
  Assets/Scripts/WeaponSwitchAbility.cs.meta
  Assets/Scripts/WeaponWheelUI.cs
  Assets/Scripts/WeaponWheelUI.cs.meta
Labels: Feature, bug
